services:
  database:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pro_tasker
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - pro_tasker
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3030:3030"
    networks:
      - pro_tasker

volumes:
  mongo_data:

networks:
  pro_tasker:
    driver: bridge
